AWSTemplateFormatVersion: "2010-09-09"
Description: S3 task using Cloudformation

Parameters:
  bucketname:
    Type: String
    Default: stelligent-u-laeticia.harperr3

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref bucketname
